apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: kupelos/event-bus:latest
---
apiVersion: v1
kind: Service
metadata:
  name: query-service
  labels:
    app: query
spec:
  selector: # what pods will the query service allow access to?
    app: query
  type: ClusterIP
  ports:
    - name: query
      protocol: TCP
      port: 4002
      targetPort: 4002
